import type { PropertyData } from '@/types'

export const DEMO_PROPERTY: PropertyData = {
  title: 'Apartamento no Centro',
  description: 'Apartamento com 3 quartos, sendo 1 suíte, sala ampla com varanda gourmet, cozinha planejada, 2 vagas de garagem e área de lazer completa. Prédio com segurança 24h.',
  price: '620000',
  priceFormatted: 'R$ 620.000,00',
  address: 'Rua das Flores, 123 - Centro',
  neighborhood: 'Centro',
  city: 'São Paulo',
  state: 'SP',
  zipCode: '01310-100',
  mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3657.197...',
  area: '125',
  bedrooms: 3,
  suites: 1,
  bathrooms: 2,
  parking: 2,
  condoFee: 'R$ 850/mês',
  iptu: 'R$ 1.200/ano',
  features: [
    'Varanda gourmet',
    'Cozinha planejada',
    'Armários embutidos',
    'Piso porcelanato',
    'Ar-condicionado',
    'Aquecimento solar',
  ],
  availableItems: [
    'Banheira de hidromassagem',
    'Box',
    'Varanda',
    'Armários no quarto',
    'Armários nos banheiros',
    'Armários na cozinha',
    'Ar condicionado',
    'Chuveiro a gás',
    'Cozinha americana',
    'Jardim',
    'Quintal',
    'Área de serviço',
  ],
  unavailableItems: [
    'Piscina privativa',
    'Apartamento cobertura',
    'Banheiro adaptado',
    'Closet',
  ],
  highlights: [
    'Piscina',
    'Academia',
    'Área gourmet',
    'Salão de festas',
    'Portaria 24h',
    'Pet friendly',
  ],
  images: [
    'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80',
    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
    'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&q=80',
    'https://images.unsplash.com/photo-1556912167-f556f1f39fdf?w=1200&q=80',
    'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80',
    'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=1200&q=80',
  ],
  agencyName: 'Luz Smart Site',
  agentName: 'João Silva',
  agentCRECI: 'CRECI-SP 123456-F',
  phone: '(11) 99999-9999',
  whatsapp: '5511999999999',
  email: 'contato@luzsmartsite.com.br',
  instagram: '@luzsmartsite',
  propertyType: 'Apartamento',
  listingType: 'venda',
  sourceUrl: '',
  extractedAt: new Date().toISOString(),
  seoTitle: 'Apartamento no Centro SP | 3 Quartos | R$ 620.000',
  seoDescription: 'Lindo apartamento no Centro de São Paulo. 3 quartos, 1 suíte, 125m², 2 vagas. Área de lazer completa, segurança 24h. Agende sua visita!',
  seoKeywords: ['apartamento centro sp', 'apartamento 3 quartos', 'apartamento à venda são paulo'],
  slug: 'apartamento-no-centro',
}
